BEGIN;

DROP TRIGGER IF EXISTS stage_dependencies_hist_trigger ON stage_dependencies;
DROP TRIGGER IF EXISTS settings_admin_hist_trigger ON settings_admin;
DROP TRIGGER IF EXISTS settings_admin_touch ON settings_admin;
DROP TRIGGER IF EXISTS settings_crm_mapping_hist_trigger ON settings_crm_mapping;
DROP TRIGGER IF EXISTS settings_crm_mapping_touch ON settings_crm_mapping;
DROP TRIGGER IF EXISTS settings_columns_hist_trigger ON settings_columns;
DROP TRIGGER IF EXISTS settings_columns_touch ON settings_columns;
DROP TRIGGER IF EXISTS settings_journal_hist_trigger ON settings_journal;
DROP TRIGGER IF EXISTS settings_journal_touch ON settings_journal;
DROP TRIGGER IF EXISTS settings_autoweight_hist_trigger ON settings_autoweight;
DROP TRIGGER IF EXISTS settings_autoweight_touch ON settings_autoweight;
DROP TRIGGER IF EXISTS excluded_statuses_hist_trigger ON excluded_statuses;
DROP TRIGGER IF EXISTS stage_capacity_hist_trigger ON stage_capacity;
DROP TRIGGER IF EXISTS stage_capacity_touch ON stage_capacity;
DROP TRIGGER IF EXISTS order_stages_hist ON order_stages;
DROP TRIGGER IF EXISTS order_stages_touch ON order_stages;
DROP TRIGGER IF EXISTS orders_hist ON orders;
DROP TRIGGER IF EXISTS orders_touch ON orders;

DROP FUNCTION IF EXISTS hist_apply_settings_admin();
DROP FUNCTION IF EXISTS hist_apply_settings_crm_mapping();
DROP FUNCTION IF EXISTS hist_apply_settings_columns();
DROP FUNCTION IF EXISTS hist_apply_settings_journal();
DROP FUNCTION IF EXISTS hist_apply_settings_autoweight();
DROP FUNCTION IF EXISTS hist_apply_excluded_statuses();
DROP FUNCTION IF EXISTS hist_apply_stage_capacity();
DROP FUNCTION IF EXISTS hist_apply_stage_dependencies();
DROP FUNCTION IF EXISTS hist_apply_order_stages();
DROP FUNCTION IF EXISTS hist_apply_orders();
DROP FUNCTION IF EXISTS touch_updated_at();
DROP FUNCTION IF EXISTS ensure_current_revision();

DROP TABLE IF EXISTS checkpoints;
DROP TABLE IF EXISTS activity_log;
DROP TABLE IF EXISTS settings_admin_hist;
DROP TABLE IF EXISTS settings_admin;
DROP TABLE IF EXISTS settings_crm_mapping_hist;
DROP TABLE IF EXISTS settings_crm_mapping;
DROP TABLE IF EXISTS settings_columns_hist;
DROP TABLE IF EXISTS settings_columns;
DROP TABLE IF EXISTS settings_journal_hist;
DROP TABLE IF EXISTS settings_journal;
DROP TABLE IF EXISTS settings_autoweight_hist;
DROP TABLE IF EXISTS settings_autoweight;
DROP TABLE IF EXISTS excluded_statuses_hist;
DROP TABLE IF EXISTS excluded_statuses;
DROP TABLE IF EXISTS stage_capacity_hist;
DROP TABLE IF EXISTS stage_capacity;
DROP TABLE IF EXISTS stage_dependencies_hist;
DROP TABLE IF EXISTS stage_dependencies;
DROP TABLE IF EXISTS order_stages_hist;
DROP TABLE IF EXISTS order_stages;
DROP TABLE IF EXISTS orders_hist;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS revisions;

COMMIT;
